"""
Build real Humboldt excess-proceeds claim dossiers from the county's own
official "Notice of Right to Claim Excess Proceeds" (R&T Code 4676),
signed under penalty of perjury by the Humboldt County Tax Collector,
published in the North Coast Journal, sourced directly from
humboldtgov.org/DocumentCenter/View/154125/excesspropub_May2026 — not
scraped, not estimated. Sale date: 2026-05-29.

This REPLACES the ~207 humboldt_*_excess_claim.md files previously in
output/dashboard/ (dated 2026-08-03), which were generated by the
pre-fix report_builder.py/predictive_scorer.py and carry the exact same
fabrication fingerprint already found and fixed elsewhere tonight — a
blanket "VERIFIED_COUNTY_RECORD" label on numbers that don't check out
(e.g. $0.00 excess proceeds paired with a live countdown timer), and in
at least one case (APN 305-073-053-000) the file's "owner" field is
literally report_builder.py's own hardcoded self-test fixture ("CASEY
B A"), not real Humboldt data at all.

Owner of record (the former owner entitled to claim) is honestly
UNVERIFIED — Humboldt's confirmed MPTS assessor index is ASMT+situs
only, no owner field (same CA privacy-law pattern as Fresno/Kern), and
no recorder cross-reference has been run yet for these 29 parcels.
Claim deadline is an approximate estimate (sale date + 365 days) —
the real deadline is one year after the Tax Collector's DEED
RECORDATION date, which is not published in this notice and is
typically a few weeks after the sale date, so the true deadline is
slightly later than the estimate here, never earlier.
"""
import sys

sys.path.insert(0, "/mnt/c/Users/chuck/Downloads/county_pipeline")
import report_builder

SALE_DATE = "2026-05-29"
APPROX_CLAIM_DEADLINE = "2027-05-29"  # sale date + 365d; real deadline is deed-recordation + 1yr, so >= this

# Source: humboldtgov.org/DocumentCenter/View/154125/excesspropub_May2026,
# extracted verbatim via pypdf 2026-08-07.
RECORDS = [
    ("016-232-003-000", "2919 Harris St, Eureka", 112106.44),
    ("021-222-006-000", "1060 O St, Arcata", 155064.34),
    ("053-172-009-000", "61 Monument Rd, Rio Dell", 7904.80),
    ("081-021-007-000", "220 Boy Scout Camp Rd, Myers Flat", 4033.19),
    ("081-021-035-000", None, 8700.34),
    ("081-021-038-000", None, 15234.09),
    ("081-021-039-000", None, 5730.99),
    ("081-021-045-000", None, 13198.15),
    ("081-081-005-000", None, 25036.59),
    ("081-081-008-000", None, 5590.38),
    ("100-012-005-000", None, 2574.20),
    ("110-201-001-000", "15 Greenbriar Ct, Shelter Cove", 7317.56),
    ("110-291-008-000", "8 Wood Ct, Shelter Cove", 3916.13),
    ("111-081-052-000", "19 Spur Ct, Shelter Cove", 526.08),
    ("111-151-066-000", None, 683.72),
    ("202-102-019-000", "3395 Rancheria Rd, Fortuna", 783.12),
    ("212-192-021-000", "164 Plymouth Acres Rd, Miranda", 3195.59),
    ("216-201-002-000", None, 11633.46),
    ("216-381-012-000", "390 River Rd, Alderpoint", 2841.64),
    ("217-121-016-000", None, 905.90),
    ("221-101-013-000", "8989 Doody Ridge Rd, Ettersburg", 23975.59),
    ("221-111-025-000", "5490 Hardwood Ln, Miranda", 15526.55),
    ("221-111-028-000", "6757 Doody Ridge Rd, Ettersburg", 49534.21),
    ("305-073-053-000", None, 11481.75),
    ("305-073-054-000", None, 10996.32),
    ("305-073-055-000", None, 7570.54),
    ("309-103-008-000", "632 Main St, Loleta", 56652.86),
    ("317-053-007-000", None, 40951.52),
    ("403-011-032-000", None, 10308.12),
    ("511-042-025-000", None, 21976.91),
]


def main():
    total = 0.0
    generated = 0
    for apn, situs, excess in RECORDS:
        total += excess
        claim_data = {
            "apn_dash": apn,
            "situs": situs,
            "owner": None,  # honestly unverified — see module docstring
            "excess_proceeds": excess,
            "claim_deadline": APPROX_CLAIM_DEADLINE,
            "deed_status": "sold_at_auction_2026-05-29",
            "source_file": (
                "Humboldt County official Notice of Right to Claim Excess Proceeds "
                "(R&T Code 4676), signed by Tax Collector Amy Christensen, executed "
                "2026-07-09, published North Coast Journal 2026-07-16/23/30 — "
                "humboldtgov.org/DocumentCenter/View/154125/excesspropub_May2026"
            ),
            "verification": (
                "VERIFIED — excess proceeds amount and sale date are from the county's own "
                "signed, published legal notice, not estimated. Owner of record (the actual "
                "claimant) is UNVERIFIED — not in this notice, no recorder cross-reference run "
                "yet. Claim deadline shown is an APPROXIMATION (sale date + 365 days); the real "
                "statutory deadline is 1 year after the Tax Collector's deed recordation, which "
                "is typically a few weeks after the sale — true deadline is >= the date shown, "
                "never earlier."
            ),
        }
        report_builder.build_excess_proceeds_report(claim_data, "humboldt")
        generated += 1

    print(f"\nGenerated {generated} real, government-sourced Humboldt excess-proceeds dossiers.")
    print(f"Total excess proceeds across all {generated} parcels: ${total:,.2f}")


if __name__ == "__main__":
    main()
