COUNTY_CONFIG = {
    "tehama": {
        "host":        "https://common1.mptsweb.com",
        "county_slug": "tehama",
        "appFolder":   "/MBC/",
        "tax_year":    "2025",
    },
    "shasta": {
        "host":        "https://common2.mptsweb.com",
        "county_slug": "shasta",
        "appFolder":   "/MBC/",
        "tax_year":    "2025",
    },
    "glenn": {
        "host":        "https://common1.mptsweb.com",
        "county_slug": "glenn",
        "appFolder":   "/MBC/",
        "tax_year":    "2025",
    },
    "colusa": {
        "host":        "https://common1.mptsweb.com",
        "county_slug": "colusa",
        "appFolder":   "/MBC/",
        "tax_year":    "2025",
    },
    "plumas": {
        "host":        "https://common1.mptsweb.com",
        "county_slug": "plumas",
        "appFolder":   "/MBC/",
        "tax_year":    "2025",
    },
    "lassen": {
        "host":        "https://common1.mptsweb.com",
        "county_slug": "lassen",
        "appFolder":   "/MBC/",
        "tax_year":    "2025",
    },
    "siskiyou": {
        "host":        "https://common1.mptsweb.com",
        "county_slug": "siskiyou",
        "appFolder":   "/MBC/",
        "tax_year":    "2025",
    },
    "trinity": {
        "host":        "https://common1.mptsweb.com",
        "county_slug": "trinity",
        "appFolder":   "/MBC/",
        "tax_year":    "2025",
    },
    "modoc": {
        "host":        "https://common1.mptsweb.com",
        "county_slug": "modoc",
        "appFolder":   "/MBC/",
        "tax_year":    "2025",
    },
    "butte": {
        "host":        "https://common2.mptsweb.com",
        "county_slug": "butte",
        "appFolder":   "/MBC/",
        "tax_year":    "2025",
    },
    "humboldt": {
        "host":        "https://common1.mptsweb.com",
        "county_slug": "humboldt",
        "appFolder":   "/MBC/",
        "tax_year":    "2025",
    },
    "kern": {
        "host":        "https://kcttc.co.kern.ca.us",
        "county_slug": "kern",
        "appFolder":   "/MBC/",
        "tax_year":    "2026",
    },
    "fresno": {
        "host":        "https://common1.mptsweb.com",
        "county_slug": "fresno",
        "appFolder":   "/MBC/",
        "tax_year":    "2026",
    },
    "riverside": {
        "host":        "https://common1.mptsweb.com",
        "county_slug": "riverside",
        "appFolder":   "/MBC/",
        "tax_year":    "2026",
    },
    "los_angeles": {
        "host":        "https://ttc.lacounty.gov",
        "county_slug": "los_angeles",
        "appFolder":   "/MBC/",
        "tax_year":    "2026",
    },
    "san_bernardino": {
        "host":        "https://common1.mptsweb.com",
        "county_slug": "sanbernardino",
        "appFolder":   "/MBC/",
        "tax_year":    "2026",
    },
    "el_dorado": {
        "host":        "https://common1.mptsweb.com",
        "county_slug": "eldorado",
        "appFolder":   "/MBC/",
        "tax_year":    "2026",
    },
    "calaveras": {
        "host":        "https://common1.mptsweb.com",
        "county_slug": "calaveras",
        "appFolder":   "/MBC/",
        "tax_year":    "2026",
    },
    "yuba": {
        "host":        "https://common1.mptsweb.com",
        "county_slug": "yuba",
        "appFolder":   "/MBC/",
        "tax_year":    "2026",
    },
    "merced": {
        "host":        "https://common1.mptsweb.com",
        "county_slug": "merced",
        "appFolder":   "/MBC/",
        "tax_year":    "2026",
    },
    "alameda": {
        "host":        "https://common1.mptsweb.com",
        "county_slug": "alameda",
        "appFolder":   "/MBC/",
        "tax_year":    "2026",
    },
}
