RECORDER_CONFIG = {
    "tehama": {
        "type": "tyler",
        "login_url": "https://recordsearch.tehama.gov/web/search/DOCSEARCH4S1",
        "name_search_url": "https://recordsearch.tehama.gov/web/search/DOCSEARCH4S1",
        "doc_search_url": "https://recordsearch.tehama.gov/web/search/DOCSEARCH4S2",
        "disclaimer_selector": "#submitDisclaimerAccept",
        "keepalive_text": ["Yes - Continue", "Yes, Continue"],
        "search_field": "#field_BothNamesID",
        "doc_search_field": "#field_DocumentNumberID",
        "search_button": "#searchButton",
        "clear_button": "#clearSearchButton",
        "results_selector": "li.ss-search-row",
        "needs_guest_login": False,
        "has_disclaimer": True
    },
    "shasta": {
        "type": "tyler",
        "login_url": "https://recorderselfservice.shastacounty.gov/web/user/disclaimer",
        "name_search_url": "https://recorderselfservice.shastacounty.gov/web/search/DOCSEARCH344S4",
        "doc_search_url": "https://recorderselfservice.shastacounty.gov/web/search/DOCSEARCH344S5",
        "disclaimer_selector": "#submitDisclaimerAccept",
        "keepalive_text": ["Yes - Continue", "Yes, Continue"],
        "search_field": "#field_BothNamesID",
        "doc_search_field": "#field_DocumentNumberID",
        "search_button": "#searchButton",
        "clear_button": "input[type='reset'][value='Clear']",
        "results_selector": ".ui-li-static",
        "needs_guest_login": False,
        "has_disclaimer": True
    },
    "butte": {
        "type": "tyler",
        "login_url": "https://recorder.buttecounty.net/web/search/DOCSEARCH481S1",
        "name_search_url": "https://recorder.buttecounty.net/web/search/DOCSEARCH481S1",
        "doc_search_url": "https://recorder.buttecounty.net/web/search/DOCSEARCH481S2",
        "disclaimer_selector": "button:has-text('I Accept')",
        "disclaimer_url_fragment": "disclaimer",
        "post_disclaimer_navigate": "https://recorder.buttecounty.net/web/search/DOCSEARCH481S1",
        "keepalive_text": [],
        "search_field": "#field_BothNamesID",
        "doc_search_field": "#field_DocumentNumberID",
        "search_button": "#searchButton",
        "clear_button": "input[type='reset'][value='Clear']",
        "results_selector": "li.ss-search-row",
        "needs_guest_login": False,
        "has_disclaimer": True,
        "adapter": "butte_recorder_adapter.py"
    },
    "lassen": {
        "type": "tyler_legacy",
        "login_url": "https://eagleweb.co.lassen.ca.us/eweb/web/loginPOST.jsp?guest=true",
        "name_search_url": "https://eagleweb.co.lassen.ca.us/eweb/web/search/DOCSEARCH4S1",
        "doc_search_url": "https://eagleweb.co.lassen.ca.us/eweb/web/search/DOCSEARCH4S2",
        "disclaimer_selector": None,
        "keepalive_text": [],
        "search_field": "#BothNamesIDSearchString",
        "doc_search_field": "#DocumentNumberIDSearchString",
        "search_button": "#searchButton",
        "clear_button": "input[type='reset']",
        "results_selector": "li.ss-search-row",
        "needs_guest_login": True,
        "has_disclaimer": False,
    },
}
